version = 4
provers_parallelism = 1

[why3]
path = "why3"
check_version = false

[altergo]
mode = "builtin"
check_version = false

[z3]
mode = "builtin"
check_version = false

[cvc4]
mode = "builtin"
check_version = false

[cvc5]
mode = "builtin"
check_version = false
