version = 5
provers_parallelism = 1

[why3]
path = "why3"
check_version = false

[why3find]
path = "why3find"
check_version = false

[altergo]
mode = "builtin"
check_version = false

[z3]
mode = "builtin"
check_version = false

[cvc4]
mode = "builtin"
check_version = false

[cvc5]
mode = "builtin"
check_version = false
