[book]
authors = ["The Creusot Contributors"]
language = "en"
src = "src"
title = "Creusot User Guide"

[output.html]
git-repository-url = "https://github.com/creusot/creusot-rs/tree/master/guide"

[output.html.playground]
runnable = false
